### ISSUE TITLE
Offers

### ISSUE THREAD

**Issue by dimitrisdervas** [dimitrisdervas/astromeria-jekyll#1]
Οι προσφορές θα είναι τελικά πάντα με αυτό το τρόπο διαρθρωμένες;
Δηλαδή κάθε δωμάτιο θα έχει μια προσφορά για συγκεκριμένες ημέρες και διαφορετική τιμή για κάθε περίοδο;

**Comment by astromeria** [comment]
ναι οι τιμες αυτες ειναι για πενθημερα δεν στο εγραψα... και ισχυουν αντιστοιχα για καθε περιοδο

**Comment by dimitrisdervas** [comment]
Εννοώ ότι και στο μέλλον θα αφορά πάντα 5νθήμερες προσφορές ή θα έχει και 3μερα και 2μερα σε προσφορά;

**Comment by astromeria** [comment]
ναι μπορει στο μελλον  μπορει να βαλουμε και 2ημερα και τριημερα.προς το παρων αυτο
