### ISSUE TITLE
Περιόδοι τιμών

### ISSUE THREAD

**Issue by dimitrisdervas** [dimitrisdervas/astromeria-jekyll#3]
θα είναι πάντα οι τρεις και θα αλλάζουν απλά οι ημερομηνίες;
Υψηλή - Μεσαία - Χαμηλή

**Comment by astromeria** [comment]
ναι θα ειναιπαντα 3 περιοδοι και οι ημερομηνιες ειναι για την ακριβεια αυτεσ που σου εχω δωσει στις προσφορες

**Comment by dimitrisdervas** [comment]
Μπορείς να αλλάξεις τους τίτλους και να προσθέσεις τα κείμενα για τα πέντε βασικά block αν παςεδω https://github.com/dimitrisdervas/astromeria-jekyll 
και μετά στο φακελο _info. Μέσα έχει δυο φακέλους για τις γλώσσες en - αγγλικά / gr - ελληνικά. Ανοιγοντας κάθε αρχείο και μετα κάνοντας κλικ στο μολυβάκι μπορείς να κάνεις edit

**Comment by dimitrisdervas** [comment]
Οι ημερομηνίες στις περιόδους θα είναι της μορφής:

```
 15/10-18/12
```

ή
    15 Oct - 18 Dec

Το πρώτο δε χρειάζεται μετάφραση το δεύτερο ομως χρειάζεται

**Comment by astromeria** [comment]
το πρωτο
