### ISSUE TITLE
Δωμάτια

### ISSUE THREAD

**Issue by dimitrisdervas** [dimitrisdervas/astromeria-jekyll#4]
Τα δωμάτια θα είναι αυτά λες στο μαιλ, αυτά που θα βλέπει ο πελάτης στο μενού και στη σελίδα "Διαμονή";

Θα έχει δηλ. το καθένα τη δική του σελίδα, θα έχουμε δηλ. διαφορετικές φωτογραφίες, περιγραφή για το καθένα;
π.χ. για το δίκλινο και για το δίκλινο με τζακι;

ή να έχουμε δίκλινο, τρίκλινο, τετράκλινο, δίχωρο
και απλά στις τιμές θα φαίνεται και μία έξτρα με το τζάκι

και το ίδιο θα ισχύει και στη φόρμα κράτησης όπου θα τα βλέπει ξεχωριστά.

Δίκλινο 
Δίκλινο με τζάκι

Τρίκλινο 
Τρίκλινο με τζάκι 

Τετράκλινο με τζάκι

Δίχωρο
Δίχωρο με τζάκι

**Comment by astromeria** [comment]
ναι ισως ειναι καλυτερα να εχουμε μια περιγραφη δικλινο,τρικλινο κτλ και να φαινεται μια εξτρα τιμη για τζακι
